data:
  dir:
    train:
      - "data/demo/dataset_trus3d-master/fold0"
      - "data/demo/dataset_trus3d-master/fold1"
      - "data/demo/dataset_trus3d-master/fold2"
      - "data/demo/dataset_trus3d-master/fold3"
      - "data/demo/dataset_trus3d-master/fold4"
    valid: "data/demo/dataset_trus3d-master/fold8"
    test: "data/demo/dataset_trus3d-master/fold9"
  format: "h5"
  type: "unpaired" # paired / unpaired / grouped
  labeled: false
  image_shape: [64, 100, 100]

tf:
  model:
    method: "ddf" # ddf or conditional or seg
    backbone:
      name: "local"
      out_kernel_initializer: "zeros" # zeros or glorot_uniform
      out_activation: ""
    local:
      num_channel_initial: 1
      extract_levels: [0, 1, 2, 3, 4]
    unet:
      num_channel_initial: 1
      depth: 2
      pooling: true
      concat_skip: false
  loss:
    similarity:
      image:
        name: "lncc"
        weight: 1
      label:
        weight: 0
        name: "multi_scale"
        multi_scale:
          loss_type: "dice"
          loss_scales: [0, 1, 2, 4, 8, 16, 32]
        single_scale:
          loss_type: "cross-entropy"
    regularization:
      weight: 5
      energy_type: "bending"
  data:
    batch_size: 2
    shuffle_buffer_num_batch: 0
  opt:
    name: "adam"
    adam:
      learning_rate: 1.0e-5
    sgd:
      learning_rate: 1.0e-4
      momentum: 0.9
    rms:
      learning_rate: 1.0e-4
      momentum: 0.9
  epochs: 10
  save_period: 2
  histogram_freq: 2
