dataset:
  dir:
    train: "demos/unpaired_ct_lung/dataset/train"
    valid: "demos/unpaired_ct_lung/dataset/test"
    test: "demos/unpaired_ct_lung/dataset/test"
  format: "nifti"
  type: "unpaired" # paired / unpaired / grouped
  labeled: true
  image_shape: [192, 192, 208]
train:
  method: "ddf" # the registration method, value should be ddf / dvf / conditional
  backbone:
    name: "local" # value should be local / global / unet
    num_channel_initial: 4 # number of initial channel in local net, controls the size of the network
    extract_levels: [0, 1, 2, 3]
  loss:
    dissimilarity:
      image:
        name: "ssd"
        weight: 0.1
      label:
        weight: 1.0
        name: "multi_scale"
        multi_scale:
          loss_type: "dice"
          loss_scales: [0, 1, 2, 4, 8, 16]
    regularization:
      weight: 0.5
      energy_type: "bending"
  preprocess:
    batch_size: 4
    shuffle_buffer_num_batch: 1
  optimizer:
    name: "adam"
    adam:
      learning_rate: 1.0e-5
  epochs: 1500
  save_period: 50
