dataset:
  dir:
    train: "demos/unpaired_mr_brain/dataset/train"
    valid: "demos/unpaired_mr_brain/dataset/test"
    test: "demos/unpaired_mr_brain/dataset/test"
  format: "nifti"
  type: "unpaired" # paired / unpaired / grouped
  labeled: True
  image_shape: [64, 64, 64]

train:
  model:
    method: "dvf" # ddf / dvf / conditional
    backbone: "unet"
    local:
      num_channel_initial: 2
      extract_levels: [0, 1, 2, 3, 4]
    unet:
      num_channel_initial: 16
      depth: 3
      pooling: false
      concat_skip: true
  loss:
    dissimilarity:
      image:
        name: "ssd"
        weight: 1.0
      label:
        weight: 0.2
        name: "multi_scale"
        multi_scale:
          loss_type: "dice"
          loss_scales: [0, 1, 2, 4, 8, 16]
        single_scale:
          loss_type: "dice"
    regularization:
      weight: 0.4
      energy_type: "gradient-l2" # bending / gradient-l2 / gradient-l1
  preprocess:
    batch_size: 4
    shuffle_buffer_num_batch: 1
    data_augmentation:
      ddf:
        field_strength: 3
        lowres_size: [9, 9, 9]
  optimizer:
    name: "adam"
    adam:
      learning_rate: 1.0e-5
    sgd:
      learning_rate: 1.0e-4
      momentum: 0.9
    rms:
      learning_rate: 1.0e-4
      momentum: 0.9
  epochs: 200
  save_period: 2
