dataset:
  dir:
    test: /home/acasamitjana/Data/Learn2Reg/valid
    train: /home/acasamitjana/Data/Learn2Reg/train
    valid: /home/acasamitjana/Data/Learn2Reg/valid
  format: nifti
  image_shape:
    - 64
    - 64
    - 64
  labeled: true
  type: unpaired
train:
  epochs: 1000
  loss:
    dissimilarity:
      image:
        name: lncc
        weight: 0.0
      label:
        multi_scale:
          loss_scales:
            - 0
            - 1
            - 2
            - 4
            - 8
            - 16
            - 32
          loss_type: dice
        name: single_scale
        single_scale:
          loss_type: dice
        weight: 2.0
    regularization:
      energy_type: gradient-l2
      weight: 0.1
  model:
    backbone: unet
    local:
      extract_levels:
        - 0
        - 1
        - 2
        - 3
        - 4
      num_channel_initial: 2
    method: dvf
    unet:
      concat_skip: true
      depth: 3
      num_channel_initial: 2
      pooling: true
  optimizer:
    adam:
      learning_rate: 1.0e-05
    name: adam
    rms:
      learning_rate: 0.0001
      momentum: 0.9
    sgd:
      learning_rate: 0.0001
      momentum: 0.9
  preprocess:
    batch_size: 5
    shuffle_buffer_num_batch: 1
  save_period: 2
