train:
  model:
    method: "ddf" # ddf / dvf / conditional
    backbone: "local"
    local:
      num_channel_initial: 16
      extract_levels: [0, 1, 2, 3, 4]
  loss:
    dissimilarity:
      image:
        name: "lncc"
        weight: 0.1
      label:
        weight: 1.0
        name: "multi_scale"
        multi_scale:
          loss_type: "dice"
          loss_scales: [0, 1, 2, 4, 8, 16, 32]
        single_scale:
          loss_type: "cross-entropy"
    regularization:
      weight: 0.5
      energy_type: "bending"
  preprocess:
    batch_size: 2
    shuffle_buffer_num_batch: 1
  optimizer:
    name: "adam"
    adam:
      learning_rate: 1.0e-4
  epochs: 500
  save_period: 50
