dataset:
  dir:
    train: "demos/unpaired_ct_abdomen/dataset/train"
    valid: "demos/unpaired_ct_abdomen/dataset/valid"
    test: "demos/unpaired_ct_abdomen/dataset/test"
  format: "nifti"
  type: "unpaired" # paired / unpaired / grouped
  labeled: true
  image_shape: [77, 64, 102] # original [192,160,256]

train:
  model:
    method: "ddf" # ddf / dvf / conditional
    backbone: "unet"
    local:
      num_channel_initial: 16
      extract_levels: [0, 1, 2, 3, 4]
    unet:
      num_channel_initial: 8
      depth: 4
      pooling: true
      concat_skip: true
  loss:
    dissimilarity:
      image:
        name: "lncc"
        weight: 0.1
      label:
        weight: 1.0
        name: "multi_scale"
        multi_scale:
          loss_type: "dice"
          loss_scales: [0, 1, 2, 4, 8, 16, 32]
        single_scale:
          loss_type: "cross-entropy"
    regularization:
      weight: 0.5
      energy_type: "bending"
  preprocess:
    batch_size: 6 # for 3 gpus
    shuffle_buffer_num_batch: 1
  optimizer:
    name: "adam"
    adam:
      learning_rate: 1.0e-4
  epochs: 500
  save_period: 50
