name: Integration Test

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  pull_request:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install graphviz
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test examples
        run: |
          pip install -e .
          pytest test/integration/test_examples.py
      - name: Test demos
        run: |
          pip install -e .
          pytest test/integration/test_demos.py
